name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  validate:
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-build-test.yml@main
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  spotless:
    needs: validate
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-spotless-check.yml@main

  integration-tests:
    needs: spotless
    runs-on: ubuntu-latest
    steps:
      - name: Clone Integration Test Repo
        uses: actions/checkout@v4
        with:
          repository: ozone-his/ozone-it
          path: ozone-it

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Integration Tests
        run: |
          cd ozone-it
          mvn clean install -pl eip-odoo-openmrs-it -am

  release:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release' }}
    needs: integration-tests
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-publish.yml@main
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
